baseurl         = "https://gileadekelvin.github.io/data-kelvin-project/"
theme           = "casper-two-edited"
languageCode    = "pt-br"
disqusShortname = "data-kelvin-project"
paginate        = 6
#SectionPagesMenu = "main"
publishDir = "docs"

[params]
  title       = "Data Kelvin Project"
  subtitle    = "Data Kelvin Project - Blog pessoal"

  cover       = "defimg/blog-cover.jpg"
  description = "Este é um blog desenvolvido e atualizado por Gileade Kelvin com o objetivo de divulgar análises e pesquisas interessantes."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "gileadekelvin"
  fbName = "gileadekelvin"
  githubName = "gileadekelvin"

  logo = "defimg/logo-dkp.png"
  orgName = "Gileade Kelvin"
  orgWebsite = "https://gileadekelvin.github.io/data-kelvin-project"
  orgDescription = "Blog Pessoal"

  author = "Gileade Kelvin"
  authorAvatar = "defimg/perfil.png"
  authorLocation = "Paraíba, Brasil"
  authorWebsite = "https://gileadekelvin.github.io/"
  authorDescription = "Estudante de Ciência da Computação na UFCG e estagiário do Ministério Público da Paraíbva desde 2017. Trabalho com Data Science no Laboratório Analytics - UFCG."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:year/:month/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "R"
  url = "/tags/R/"
  weight = 100

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 100

[[menu.main]]
  name = "Categorias"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "R"
  url = "/categories/R/"
  weight = 99

[[menu.main]]
  name = "Sobre"
  url = "/about"
  weight = 95
